# Generated by Django 4.0.3 on 2022-04-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
    ]
